### ISSUE TITLE
tip marker

### ISSUE THREAD

**Issue by parengreggie** [MrToph/react-native-progress-circle#11]
Hi MrToph,

is it possible to make/have this little circular marker at the tip?

![progress circle](https://user-images.githubusercontent.com/14164152/36081273-60e04c10-0fd7-11e8-80e3-2e47c1efbc91.png)

thanks.

image for reference only.
like your library. very easy to use.

**Comment by MrToph** [comment]
It's currently not supported. This component still has a pretty basic feature set, but feel free to create a PR.
