### ISSUE TITLE
Can the background color be transparent?

### ISSUE THREAD

**Issue by tc** [MrToph/react-native-progress-circle#13]
I tried ``bgColor='rgba(52, 52, 52, 0.8)'`` and ``bgColor='transparent'``

**Comment by MrToph** [comment]
No, this unfortunately doesn't work with the way the current implementation works.

**Comment by DoWhileGeek** [comment]
That's the only thing that disqualified this lib for my project. 😢

**Comment by BeKnowDo** [comment]
Damn...well that sucks
