### ISSUE TITLE
Is it compatible with react-native v0.57.4?

### ISSUE THREAD

**Issue by qasimalbaqali** [MrToph/react-native-progress-circle#19]
I'm in process of upgrading my app which is using `react-native-progress-circle` v2.0.1, will it be compatible if I upgrade the `react-native` version to 5.7?

**Comment by MrToph** [comment]
I guess so, it's just JavaScript and unless they heavily reworked the yoga layout engine, I don't see why not.

Just try it.

**Comment by jonathangreco** [comment]
Hi @MrToph.
Actually, not so much. There is a small graphical bug with the latest version. The progress circle is not a circle anymore, it seems that it's a rectangle or something similar.

If you can test it to confirm, I'll appreciate

**Comment by limaAniceto** [comment]
React Native 0.57.4 and the issue still happens

**Comment by baicuhaha** [comment]
Much to my regret  ！React Native 0.57.7 and the issue still happens

**Comment by halaharr** [comment]
Is this issues resolved. I am having issues with 0.59.8?
