### ISSUE TITLE
componentWillReceiveProps is deprecated

### ISSUE THREAD

**Issue by lizzard77** [MrToph/react-native-progress-circle#25]
When using the component with RN 0.59, I get this warning:

![image](https://user-images.githubusercontent.com/15921685/58561143-c3642880-8226-11e9-8077-771f84aa7f3b.png)

**Comment by malikmani** [comment]
Anyone willing to fix this warning?

**Comment by mgenov** [comment]
+1 on this too. 

It would be nice if #32 could be merged and a new version to be dumped.

**Comment by jordibruin** [comment]
@MrToph could you merge #32 please? Thanks! 🙂
