### ISSUE TITLE
Weird shape

### ISSUE THREAD

**Issue by zumoshi** [MrToph/react-native-progress-circle#3]
hello,

I have tried to use your library, however, for some reason, the outer circle is not round!
![2017-07-31 17_55_02-genymotion for personal use - samsung galaxy s3 - 4 1 1 - api 16 - 720x1280 720](https://user-images.githubusercontent.com/4184939/28779850-e7092c4c-7619-11e7-9f94-920b1a9b131d.png)

I have copied the example code from your readme, it is the only thing returned by the render function, so I don't think it is the result of interference from styles of other parts of the code.

react-native version: 0.44.0
android api: 16 (emulator with 720x1280 resolution)

what do you think can cause this behavior?

thanks in advance.

**Comment by MrToph** [comment]
I have no idea why this could happen to be honest. Android API 16 is quite old, does the issue still exist in API 22?

**Comment by zumoshi** [comment]
sorry for the late reply, I missed the email notification...

no, it seems to work fine on API 22
![image](https://user-images.githubusercontent.com/4184939/28996782-a6de6ad2-7a1b-11e7-8ad4-f510efc60bba.png)

but the shape morphs as it fills in Android 4.1, 
![image](https://user-images.githubusercontent.com/4184939/28996795-eeda8ece-7a1b-11e7-9beb-1bc72c03b771.png)

until finally reaching this shape:
![image](https://user-images.githubusercontent.com/4184939/28996818-2f03d8ac-7a1c-11e7-8b20-caaef3970a1d.png)

if it was a problem with how api 16 handles the border-radius, it should've affected the inner circle too, I have no clue what could cause it neither. would you be interested in investigating the issue? or is api 16 too old to be worth supporting?

**Comment by MrToph** [comment]
I don't see any mistake in my code that would cause such a behavior. This makes me believe that something is wrong within react-native and their `css border-radius` implementation in API 16.
Unfortunately, there's nothing I can do here.

**Comment by muhaimincs** [comment]
unfortunately this still occured in react-native ~0.49.5

**Comment by est7** [comment]
add MAGICNUMBER ...

renderHalfCircle (rotateDegrees, halfCircleStyles) {
    const { radius, color } = this.props
    return (
      <View
        style={[
          styles.leftWrap,
          {
            width: radius,
            height: radius * 2
          }
        ]}
      >
        <View
          style={[
            styles.halfCircle,
            {
              width: radius,
              height: radius * 2,
              borderRadius: radius + MAGICNUMBER,
              transform: [
                { translateX: radius / 2 },
                { rotate: `${rotateDegrees}deg` },
                { translateX: -radius / 2 }
              ],
              backgroundColor: color,
              ...halfCircleStyles
            }
          ]}
        />
      </View>
    )
  }

**Comment by ahmedfares** [comment]
I meet the problem of weird circle when I configure the phone to language (right to left) and it works fine when the language is english .. can any one help me 
![Untitled](https://user-images.githubusercontent.com/4611069/54070612-bad50500-426a-11e9-9fef-80ce9fb28a92.png)
