### ISSUE TITLE
How to animate it?

### ISSUE THREAD

**Issue by syampolskiy** [MrToph/react-native-progress-circle#5]
can not find in documentation how to animate progress circle filling

**Comment by MrToph** [comment]
Hi, this is a non-animated component. If you're looking for something like a timer I also have [this component](https://github.com/MrToph/react-native-countdown-circle).

If you want this component to have a `fill` animation, it's currently not possible 😬  
But you can have a look at the other animated component and try it yourself

**Comment by g33ktony** [comment]
@syampolskiy you can use Animated with a listener to update a state with the value while changing.

const progress = React.useRef(new Animated.Value(0))
const [animatedProgress, setAnimatedProgress] = React.useState(0)

Animated.timing(progress.current, {
        toValue: props.percentage,
        delay: 500,
        duration: 750,
        easing: Easing.inOut(Easing.quad),
        useNativeDriver: true
      }).start()

progress.current.addListener(animated =>setAnimatedProgress(animated.value))
