### ISSUE TITLE
how to set progress-circle style ?

### ISSUE THREAD

**Issue by JeckChou** [MrToph/react-native-progress-circle#9]
Hi,
I am using this lib, but i can not set style to ProgressCircle, it is not working.

this is my code
` <ImageBackground style={styles.backgroundImage} imageStyle={styles.imageStyle} source={require('../img/img2.png')} >
                    {/* <Text style={{ fontSize:20 , color:0XFF0000FF,marginBottom:100}}>JECK</Text> */}
                    <ProgressCircle
                    style={{ marginBottom: 100 }}
                        percent={30}
                        radius={20}
                        borderWidth={8}
                        color="#3399FF"
                        shadowColor="#999"
                        bgColor="#fff">
                    </ProgressCircle>
                </ImageBackground>`

Text component is work with marginbottom, but ProgressCircle is not. can you help me ? thanks

**Comment by MrToph** [comment]
Hi,
Yes, you cannot style the `ProgressCircle` this way.

You need to wrap it in a `View` and set the margin-bottom on the `View`

**Comment by JeckChou** [comment]
thanks for your reply and I will try yours.

@MrToph thank you again.

**Comment by JeckChou** [comment]
wrap in a `view` is a solution.  

thanks
